@startuml

abstract class User {
    - id: int
    - firstName: string
    - lastName: string
    - email: string
    - password: string
    + login()
    + logout()
}

class Customer extends User {
    - status: UserStatus
    + addPaymentCard()
    + createBooking()
}

class Admin extends User {
    + manageMovies()
    + manageUsers()
}

class PaymentCard {
    - cardNumber: string
    - billingAddress: string
    - expirationDate: Date
    + validateCard()
    + updateCardInfo()
}

class FavoriteMovies {
    - movie: Movie
    + addMovie()
    + removeMovie()
}

enum UserStatus {
    ACTIVE
    SUSPENDED
    INACTIVE
}

class Booking {
    - bookingId: int
    - total: int
    - bookingDate: Date
    + addTicket()
    + applyPromotion()
}

class Ticket {
    - ticketId: int
    - seatNumber: int
    - type: UserTypes
    + assignSeat()
    + calculatePrice()
}

class Promotion {
    - promoCode: string
    - discount: double
    + validatePromotion()
    + applyDiscount()
}

class UserTypes {
    - id: int
    - type: string
    - price: double
}

class Theater {
    - theaterId: int
    - name: string
    + addShowroom()
    + removeShowroom()
}

class Show {
    - showId: int
    - showTime: DateTime
    - duration: int
    + scheduleShow()
    + cancelShow()
}

class ShowRoom {
    - showroomId: int
    - seatCount: int
    + getAvailableSeats()
    + assignSeat()
}

class Movie {
    - movieId: int
    - title: string
    - category: string
    - duration: int
    + updateMovie()
    + getDetails()
}

Customer "1" *-- "0..3" PaymentCard
Customer "1" *-- "0..*" FavoriteMovies
Customer "1" *-- "0..*" Booking
FavoriteMovies "*" -- "1" Movie

Booking "1" *-- "1..*" Ticket
Booking "1" -- "0..1" Promotion
Booking "*" -- PaymentCard

Theater "1" *-- "1..*" ShowRoom
Movie "1" -- "0..*" Show
ShowRoom "1" -- "0..*" Show
Show "1" -- "1..*" Ticket
Ticket "*" -- "1" UserTypes

Admin -- Movie
Admin -- Promotion
Admin -- User

@enduml