@startuml

abstract class User {
    - id: int
    - firstName: string
    - lastName: string
    - email: string
    - password: string
    + login()
    + logout()
}

class Customer extends User {
    - status: UserStatus
    + addPaymentCard()
    + createBooking()
}

class Admin extends User {
    + manageMovies()
    + manageUsers()
}

class PaymentCard {
    - cardNumber: string
    - billingAddress: string
    - expirationDate: Date
    + validateCard()
    + updateCardInfo()
}

class FavoriteMovies {
    - movie: Movie
}

enum UserStatus {
    ACTIVE
    SUSPENDED
    INACTIVE
}

class Booking {
    - bookingId: int
    - total: int
    - bookingDate: Date
    + addTicket()
    + applyPromotion()
}

class Ticket {
    - ticketId: int
    - seatNumber: int
    - type: UserTypes
    + assignSeat()
    + calculatePrice()
}

class Promotion {
    - promoCode: string
    - discount: double
    + validatePromotion()
    + applyDiscount()
}

class UserTypes {
    - id: int
    - type: string
}

class Show {
}

class ShowRoom {
}

class Movie {
}

Customer "1" *-- "0..3" PaymentCard
Customer "1" -- "0..*" FavoriteMovies
Customer "1" *-- "0..*" Booking

Booking "1" -- "1..*" Ticket
Booking "1" -- "0..1" Promotion
Booking "*" -- PaymentCard

@enduml