@startuml

abstract class User {
    - id: int
    - firstName: string
    - lastName: string
    - email: string
    - password: string
}

class Customer extends User {
    - status: UserStatus
}

class Admin extends User {
    - name:string
    - userId: string
    - password: string
}

class PaymentCard {
    - cardNumber: string
    - billingAddress: string
    - expirationDate: Date
}

class FavoriteMovies {
    - movieName: string
}

enum UserStatus {
    ACTIVE
    SUSPENDED
    INACTIVE
}

Customer "1" *-- "0..3" PaymentCard
Customer "0...*" *-- "1" FavoriteMovies

@endum